[workspace]
resolver = "2"
members = [
    "android/translations-converter",
    "mullvad-daemon",
    "mullvad-cli",
    "mullvad-setup",
    "mullvad-problem-report",
    "mullvad-jni",
    "mullvad-paths",
    "mullvad-types",
    "mullvad-rpc",
    "mullvad-exclude",
    "talpid-openvpn-plugin",
    "talpid-core",
    "talpid-dbus",
    "talpid-platform-metadata",
    "mullvad-management-interface",
	"tunnel-obfuscation",
]
exclude = ["dist-assets/binaries/shadowsocks-rust"]

[profile.release]
opt-level = 3
lto = true
